# Generated by Django 6.0 on 2026-01-01 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf/Veuve')], default='SINGLE', max_length=10, verbose_name='Situation matrimoniale')),
                ('nationality', models.CharField(default='Française', max_length=50, verbose_name='Nationalité')),
                ('id_card_number', models.CharField(blank=True, max_length=50, verbose_name="N° Carte d'identité")),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Tél. contact d'urgence")),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='personnel.department', verbose_name='Département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI - Contrat à Durée Indéterminée'), ('CDD', 'CDD - Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('APPRENTISSAGE', "Contrat d'Apprentissage"), ('FREELANCE', 'Freelance/Prestation'), ('INTERIM', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('work_schedule', models.CharField(choices=[('FULL_TIME', 'Temps plein (35h/semaine)'), ('PART_TIME', 'Temps partiel'), ('VARIABLE', 'Horaires variables')], default='FULL_TIME', max_length=20, verbose_name='Régime de travail')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Heures hebdomadaires')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base (€/mois)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taux horaire (€/h)')),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prime de repas (€/jour)')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Indemnité transport (€/mois)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrat actif')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Document du contrat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Congé annuel'), ('SICK', 'Congé maladie'), ('MATERNITY', 'Congé maternité'), ('PATERNITY', 'Congé paternité'), ('UNPAID', 'Congé sans solde'), ('FAMILY', 'Congé familial'), ('SPECIAL', 'Congé spécial')], max_length=20, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('days_count', models.IntegerField(verbose_name='Nombre de jours')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Raison du refus')),
                ('document', models.FileField(blank=True, null=True, upload_to='leaves/%Y/%m/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'Retard'), ('LEAVE', 'Congé'), ('SICK', 'Maladie'), ('REMOTE', 'Télétravail')], max_length=10, verbose_name='Statut')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures travaillées')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures supplémentaires')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant heures sup.')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Indemnités')),
                ('absences_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déduction absences')),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cotisations sociales')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impôts')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres déductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(default='Virement bancaire', max_length=50, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
