# Generated by Django 6.0 on 2026-01-07 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, unique=True, verbose_name='N° de table')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacité (personnes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='TableLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=50, unique=True, verbose_name='N° de réservation')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('reservation_date', models.DateField(verbose_name='Date de réservation')),
                ('time_slot', models.CharField(choices=[('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], max_length=10, verbose_name='Créneau horaire')),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Nombre de personnes')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('NO_SHOW', 'Client absent'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Demandes spéciales')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='bookings.table', verbose_name='Table assignée')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-reservation_date', '-time_slot'],
                'unique_together': {('table', 'reservation_date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Créée'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('MODIFIED', 'Modifiée'), ('COMPLETED', 'Terminée'), ('NO_SHOW', 'Client absent')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Effectué le')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Historique de réservation',
                'verbose_name_plural': 'Historique des réservations',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='bookings.tablelocation', verbose_name='Emplacement'),
        ),
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_slot', models.CharField(choices=[('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00')], max_length=10, verbose_name='Créneau horaire')),
                ('max_reservations', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Réservations maximum')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilité créneau',
                'verbose_name_plural': 'Disponibilités créneaux',
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
