# Generated by Django 6.0 on 2026-01-07 18:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône FontAwesome')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de menu',
                'verbose_name_plural': 'Catégories de menu',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (€)')),
                ('track_inventory', models.BooleanField(default=False, help_text='Déduire automatiquement du stock quand commandé', verbose_name='Suivre le stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Image')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('preparation_time', models.IntegerField(blank=True, null=True, verbose_name='Temps de préparation (min)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Végétarien')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Végan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Sans gluten')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Épicé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='orders.menucategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='N° de commande')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Sur place'), ('TAKEAWAY', 'À emporter'), ('DELIVERY', 'Livraison')], default='DINE_IN', max_length=20, verbose_name='Type de commande')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY', 'Prête'), ('SERVED', 'Servie'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmée le')),
                ('preparing_at', models.DateTimeField(blank=True, null=True, verbose_name='En préparation le')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Prête le')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='Servie le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total (€)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA (€)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise (€)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total (€)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_served', to=settings.AUTH_USER_MODEL, verbose_name='Servi par')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bookings.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='N° ticket')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], default='NEW', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commencé à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Ticket de cuisine',
                'verbose_name_plural': 'Tickets de cuisine',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PREPARING', 'En préparation'), ('READY', 'Prêt'), ('SERVED', 'Servi'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.menuitem', verbose_name='Plat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité nécessaire')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='orders.menuitem', verbose_name='Plat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='inventory.product', verbose_name='Ingrédient')),
            ],
            options={
                'verbose_name': 'Ingrédient du plat',
                'verbose_name_plural': 'Ingrédients des plats',
                'unique_together': {('menu_item', 'product')},
            },
        ),
    ]
